### ISSUE TITLE
a runed ironwood sheaf arrow

### ISSUE THREAD

**Issue by GeneralGormal** [torilmud/issues#419] opened 2018-06-03 14:47 UTC
These got overlooked with the recent arrow changes.  To get them you need a Muspelheim rare to open the lair and then fight 3x red dragons together and a then single, perma-shielded ancient red in a silent room.

**Comment by ghost** [comment] 2018-11-19 04:42
i'm with jake on this, it's of the weaker dice/bonus arrow class, but it is def not farmable, should get some kind of enchantment

**Comment by gruumsh** [comment] 2019-10-04 02:17
Ok, open to suggestions. I think last time jake and i discussed this we talked about flaming burst.

**Comment by shevarash** [comment] 2023-02-20 19:46
This is a duplicate of a newer issue. We'll track it with that one and close this.

**Closed as not planned by shevarash** 2023-02-20 19:46 UTC
Labels: areas
