### ISSUE TITLE
Powers Trip and Sweeping Strike: Wait times seem off...

### ISSUE THREAD

**Issue by projectx43** [torilmud/issues#557] opened 2019-05-14 22:30 UTC
Rogues using legacy trip used to be able to perform an action after 8 sec, unlike bash that was 12. I always assumed this was to say that Rogues were higher dexterity than Warriors and could keep 2 mobs down if timed correctly. Worked like: Recharge Time 8 seconds. Target Effect: Wait for 12 seconds.

Also assume that Sweeping Strike for Rangers is meant to be an "equivalent" without granting legacy trip skill.

Sweeping Strike has: Recharge Time: 12 sec. Target Effect: Wait for 8 seconds, leaving an empty round of either fleeing or spell casting.

Dominating Strike has Recharge Time 12 sec. Target Effect: Wait for 12 seconds. (Like legacy Bash)

Seems like Sweeping Strike has Recharge Time and Target Effect backwards.

**Comment by GeneralGormal** [comment] 2019-05-17 15:50
Someone asking for ranger buffs *lul*

**Comment by projectx43** [comment] 2019-05-17 18:09
It's a valid question.

When legacy trip is removed, it's going to impact rogues too. 

Legacy skills (Mounted Charge, Trip, Bash... whatever) used to lock the target for the 12 sec equivalent, as I recall.

Big question: Is this effect intentional or an oversight? Could the rogue trip power have been an oversight and sweeping strike just been copied off of trip power, thus making it incorrect too?

**Comment by shevarash** [comment] 2019-05-20 19:11
Something does seem a little off here.

* Legacy trip actually lags the target for 6 seconds, and the tripper for 8 seconds. 
* Powers trip lags the target for 8 seconds and the tripper for 8 seconds. 

What seems likely is that legacy trip was intended to be not quite as dependable as bash, but then I corrected that when converting the power. Then, Sweeping Strike somehow ended up with the recharge of bash (12 seconds), but the lag time of trip. I don't recall this being intentional, and it doesn't make much sense.

_Sweeping Strike_ should probably be adjusted to have a 12 second target lag time.

**Comment by projectx43** [comment] 2019-05-22 00:57
Thanks Shev

**Comment by beshaba-toril** [comment] 2019-09-09 22:40
Merged 9/4

**Closed as completed by beshaba-toril** 2019-09-09 22:40 UTC
Labels: bug, powers, classes
