### ISSUE TITLE
Crimson Hand door not working

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#1009] opened 2023-08-19 14:44 UTC
I checked with Lilithelle and she can do it fine in testmud, but for some reason the main mud door isn't working?  I'm not sure if something else is added for "bleed" that is messing it up, but i don't have any aliases or triggers and on main mud it also wasn't working for her, so with two people I'm thinking it's not a client side issue. Please take a look.

< 511h/508H 89p/89P 166v/166V >
< P: std > TICK IN 5 SECONDS.
---------------------------ASSASSINATE READY-----------------------
look
Before a Blackened Temple
Exits: -W
A massive stone slab, bearing a crimson hand symbol blocks the doorway.

< 511h/508H 89p/89P 166v/166V >
< P: std > bleed idol
That person is not here, so you put the blood back into the wound.

< 511h/508H 89p/89P 166v/166V >
< P: std > bleed toppled
That person is not here, so you put the blood back into the wound.

< 511h/508H 89p/89P 166v/166V >
< P: std > bleed scorhed
That person is not here, so you put the blood back into the wound.

**Comment by marthammor** [comment] 2023-08-19 15:11
Right command, wrong place. Working as intended. Closing ticket.

**Closed as completed** 2023-08-19 20:30 UTC
