### ISSUE TITLE
Bug: flee does NOT abort spellcasting. Im casting in one room, fleeing, ending spell in another.

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#228] opened 2017-10-23 17:11 UTC
**Currently "You flee" triggers "abort" to solve this. It spams, but works. Should auto-abort on flee, IMO.**

< 499h/836H 232v/233V >
< >
A Ring of Rowan Trees
A few scattered blood droplets cover the area.
A large pool of water which glints silver fills the area.
A large rowan tree stands sentinel here.
A large rowan tree stands sentinel here.
A large rowan tree stands sentinel here.
A large rowan tree stands sentinel here.
A large rowan tree stands sentinel here.
A large rowan tree stands sentinel here.
A large rowan tree stands sentinel here.
< 500h/836H 232v/233V >
< > You start chanting...
a large rowan tree misses you with its bludgeon.
a large rowan tree misses you with its bludgeon.
a large rowan tree critically wounds you with a massive bludgeon!
OUCH!  That really did HURT!
South Side of the Hill
Lilithelle - Valkyrie - Shadows of Imphras (Moon Elf) stands in mid-air here.
The faerie sage, Tatterfoal is stretched out, sound asleep.
You flee northward!
< 344h/836H 231v/233V >
< >
Casting: Prismatic Spray **
< 346h/836H 233v/233V >
< >

Casting: Prismatic Spray *
< 346h/836H 233v/233V >
< > You're busy spellcasting!
< 347h/836H 233v/233V >
< >
You complete your spell...
You send a rainbow of prismatic spray from you hands.
Your spell fails to take hold on The faerie sage, Tatterfoal.
The faerie sage, Tatterfoal has a RUDE awakening!
The faerie sage, Tatterfoal awakens.

**Comment by marthammor** [comment] 2017-11-07 07:13
Looks like this was perhaps caused by hitting wimpy and fleeing?
If so, its fixed. If not, please re-open the ticket.
You now abort when wimpy fleeing if you're casting. Waiting on move. Closing ticket.

**Closed as completed by marthammor** 2017-11-07 07:13 UTC
Labels: bug
